name: devPipeline
on:
  push:
    branches:
      - 'c368team03'
jobs:
  dev-commit-triggered-conditional-builds:
    name: Full Commit Triggered Conditional Builds
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          fetch-depth: 2

      - name: Check Changed
        id: files-changed
        shell: pwsh
        run: |
          $diff = git diff --name-only HEAD^ HEAD
          echo "$diff"
          $currencyAPIDiff = $diff | Where-Object { $_ -match '^src/currencyAPI/' -or $_ -match '.md$' }
          $cHasDif = $currencyAPIDiff.Length -gt 0
          $feDiff = $diff | Where-Object { $_ -match '^src/nginx/' -or $_ -match '.md$' }
          $feHasDif = $feDiff.Length -gt 0
          $dbDiff = $diff | Where-Object { $_ -match '^src/mysql/' -or $_ -match '.md$' }
          $dbHasDif = $dbDiff.Length -gt 0
          $apiDiff = $diff | Where-Object {$_ -match '^src/fastapi/' -or $_ -match '.md$' }
          $apiHasDif = $apiDiff.Length -gt 0
          Write-Host "::set-output name=capi_changed::$cHasDif"
          Write-Host "::set-output name=fe_changed::$feHasDif"
          Write-Host "::set-output name=db_changed::$dbHasDif"
          Write-Host "::set-output name=api_changed::$apiHasDif"
          echo "currencyAPI changed = $cHasDif"
          echo "FE changed = $feHasDif"
          echo "DB changed = $dbHasDif"
          echo "API changed = $apiHasDif"



      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Print Run Number
        run: echo ${{ github.run_number }}

      - name: Build and Push Front End
        id: build-img-fe
        if: steps.files-changed.outputs.fe_changed == 'True'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: "production-support-course"
          ECR_RR: "108174090253.dkr.ecr.us-east-1.amazonaws.com/production-support-course"
          BRANCH: 'c368team03'
          TAG: "c368team03fe-dev-${{github.run_number}}"
        run: |
          echo "Building FE"
          docker build -f ${{github.workspace}}/Dockerfiles/Dockerfile_nginx -t $ECR_RR:$TAG .
          echo "Pushing IMG to ECR"
          docker push $ECR_RR:$TAG

      - name: Build and Push DB
        id: build-img-db
        if: steps.files-changed.outputs.db_changed == 'True'
        env:
          ECR_RR: "108174090253.dkr.ecr.us-east-1.amazonaws.com/production-support-course"
          TAG: "c368team03db-dev-${{github.run_number}}"
        run: |
          echo "Building DB"
          docker build -f ${{github.workspace}}/Dockerfiles/Dockerfile_mysql -t $ECR_RR:$TAG .
          echo "Pushing IMG to ECR"
          docker push $ECR_RR:$TAG

      - name: Build and Push currencyAPI
        id: build-img-currencyapi
        if: steps.files-changed.outputs.capi_changed == 'True'
        env:
          ECR_RR: "108174090253.dkr.ecr.us-east-1.amazonaws.com/production-support-course"
          TAG: "c368team03currency-api-dev-${{github.run_number}}"
        run: |
          echo "Building CurrencyAPI"
          docker build -f ${{github.workspace}}/Dockerfiles/Dockerfile_currencyAPI -t $ECR_RR:$TAG .
          echo "Pushing IMG to ECR"
          docker push $ECR_RR:$TAG

      - name: Build and Push API
        id: build-img-api
        if: steps.files-changed.outputs.api_changed == 'True'
        env:
          ECR_RR: "108174090253.dkr.ecr.us-east-1.amazonaws.com/production-support-course"
          TAG: "c368team03api-dev-${{github.run_number}}"
        run: |
          echo "Building API"
          docker build -f ${{github.workspace}}/Dockerfiles/Dockerfile_fastapi -t $ECR_RR:$TAG .
          echo "Pushing IMG to ECR"
          docker push $ECR_RR:$TAG
